README.md

I was a little bit confused about the process / links / etc behind the weekly reports vs. monthly team meetings. This attempts to clarify the language around those a bit so that it's easier to orient oneself to the hackmd vs. the archives etc.
Figured this one could use a little discussion, so I made this in a separate PR from the weekly report addition from the last meeting!

update readme to clarify links / process of weekly reports

---

README.md

@willingc caught a bug in readthedocs yesterday that resulted in a bunch of broken docs builds. This can be difficult to spot since our documentation for each repo is on a different page. This collects the badges for several jupyterhub-related repositories in one place, so we can see if they're broken or not quickly.

Update README.md with docs badges for many repos

---

README.md

I wrote "Operational Scalability" like Yuvi, as I have mainly worked
on z2jh and related projects.

Self adding to jh-maintainer list

---

README.md

This adds a row where we can put links to the changelogs for each of the major sub-projects of JupyterHub. Note that in putting this PR together, I realized that several of our repos actually don't have changelogs :-)  I've decided to add it anyway in the hopes that this encourages us to start putting more information into our releases, which will increase the likelihood that other people start using and contributing!

adding a row for changelogs

---

docs/index.rst
docs/team.rst

This updates the "team" page to use an rST table and includes emojis from the kent-dodds contributions project. The goal is to make it easier for people to express their contributions to the project with a vocabulary of emojis that span many different kinds of contribution (not just code).
I took a stab at finding emojis for the things that people had already listed, but please feel free to make edits to this PR or another PR if you'd like yours updated! If you did not list any "official" role within the JupyterHub world, I didn't choose any emojis but please do add whatever you'd like!

updating teams with emojis

---

README.md

Adds a link to the "teams" page in the readme:
closes #71

adding team to readme

---

docs/index.rst
docs/milestones.rst

This adds a link to the milestones of various JupyterHub projects to the team compass repo

adding milestones to the team compass page

---

docs/meetings.rst

adds a calendar for upcoming team meetings to the meetings page

adding a public page for meetings

---

docs/conf.py
docs/team/contributors-jupyterhub.yaml

Added myself to the contributor list, thanks to @choldgraf's invitation in #86 :)
Also, I noticed the links to everyone's github pages were broken because the `@` wasn't stripped for their username. I added logic to fix this issue.

Add myself to contributor list and fix broken links

---

docs/milestones.rst

Updates the roadmaps page with a bit more info, and links to new roadmaps in the jupyterhub ecosystem

updating roadmaps page

---

docs/_static/custom.css
docs/binder_governance.rst
docs/conf.py
docs/scripts/gen_contributors.py
docs/team.rst
docs/team/contributors-binder.yaml
docs/team/contributors-jupyterhub.yaml

This does the following:
* Makes the "definitive" list whatever is on the "teams" page instead of embedded in the governance doc.
* Adds the team colors to the teams page
* Factors out the teams page creation into a separate script to make it easier to maintain.
cc @betatim this was the PR I had originally made to your branch
Here's how it looks! https://68-113493831-gh.circle-artifacts.com/0/html/team.html

Moving definitive list to the team page

---

docs/index.rst
docs/tools.rst

This adds a "tools" page to the team-compass that we could use to provide links / explanations for the various tools at use in the organization.
I started it off by adding the greasemonkey/tampermonkey script that puts a button to
the built documentation on each PR page (for repositories that build a preview version
of the docs with CircleCI).

addinng a tools section and documentation button JS

---

README.md
docs/index.rst
docs/meetings.rst

This PR does a couple things:
* Updates the badges in README to remove the cauldron stats page, and provide a link to the monthly agenda page, closes #30 
* Adds links / steps for updating the agenda, hopefully to make it easier
One thing to note: this suggests a slight difference in how we update the agenda. Instead of using a new hackmd for each monthly meeting, we cut / paste the meeting agenda text into a markdown file for our team meeting archive, then copy / paste the agenda template into the same HackMD. This way we don't have to update the link to the monthly agenda on the README / website each day, but it means we need to remember to keep re-using the same HackMD instead of creating a new one. @Zsailer and @betatim since you've been doing a lot of the work around this now/in the …

updating badges and team meeting links

---

docs/monthly-meeting/2019-03-21.md

Zoom lets us share the recorded video directly from their webpage. I've added the link to the meeting's minutes. There's even a transcript of the meeting next to the call which is cool. 
This doesn't really advertise the video much. It's just a link in the meeting minutes. I'm not sure how to embed the video in the sphinx page unless it's a youtube video. Even then, I think it requires a sphinx extension...
I can look into uploading the video to the Jupyter/IPython youtube channel if we think it's worth doing. What do other's think?

Link to march meeting video

---

docs/contributing.md
docs/index.rst
docs/meetings.rst

We've got a few contributing guides in specific repositories, but I couldn't find a "meta" contributing guide that helps point people in the right direction. I was inspired by [@emdupre's version](https://github.com/jupyter/jupyter-book/blob/master/CONTRIBUTING.md) of @kirstiejane's STEMMRoleModels contributing guide, and put something like this together for the team compass repository.
Would love feedback if folks have ideas!
Note that this also overlaps with some of the content in the [original jupyter contributing guide](https://jupyter.readthedocs.io/en/latest/contributor/content-contributor.html). If that's a better place for this, perhaps we can work to update it there as well? (maybe @willingc has thoughts on that?)

contributing guide

---

docs/binder_governance.rst

Follow up #142 by adding the comms expectation to the governance document.
closes #142

Make the expectation that team members watch this repository explicit

---

docs/team/contributors-binder.yaml

Hey all - over the last few months, @sgibson91 has been helping out teaching others, opening issues/PRs, and being active in the Gitter channel and on team meetings. She's maintaining the BinderHub at the Turing Institute and has been growing the Binder community in her neck of the woods.
This PR adds Sarah G. to the blue team! I think she'd be a great addition!
Here's what the page will looks like: https://113-113493831-gh.circle-artifacts.com/0/html/team.html#binder-team
(note that I haven't added in the "what you help out with" part of the data because I didn't want to make assumptions for Sarah, but if you'd like to update this yourself, feel free to do so either as a suggested change to this PR, or as a follow-up PR!)
also pinging the @jupyterhub/binder-team so they have a chance to …

Adding Sarah to the blue team

---

docs/binder/governance.rst
docs/index.rst
docs/team/adding-members.rst
docs/team/member-guide.md

This adds onboarding documentation from #114 and #113. There were still some conversations to be finished there, so feel free to ask for changes etc. In particular @lheagy's suggestion about onboarding review processes etc is a good idea though I'm not sure where exactly to point people on that front...perhaps that's for another PR to include documentation about expected team behavior and opportunities to contribute?
I'm gonna follow the checklist to onboard @sgibson91 as well, follow along in https://github.com/jupyterhub/team-compass/issues/168
This closes #114 and #113 (though we will probably need to update these docs over time).

adding onboarding docs

---

docs/index.rst
docs/talking.rst

This adds a page with information about giving talks or just generally discussing the JupyterHub and Binder projects.
As a part of this PR there are also two new "wiki-style" community forum threads:
* https://discourse.jupyter.org/t/binder-jupyterhub-common-questions-and-suggested-answers/1686/2
* https://discourse.jupyter.org/t/resources-for-giving-talks-about-the-jupyterhub-and-binder-projects/1685/2
Would love to hear what folks think! In particular @betatim , @sgibson91 , and @kirstiejane who all had thoughts on this in the last team meeting
closes #179

adding docs on talking about the project

---

docs/binder/governance.rst
docs/governance.rst
docs/index.rst
docs/team.rst
docs/team/member-guide.md

This PR does a couple of things on the team compass repo to try and add missing information and reorganize to make things easier to find.
* Adds a JupyterHub governance page - this is largely a copy of the Binder governance page with a few modifications to fit the JupyterHub team dynamics
* This includes the following JupyterHub team roles: Team Leader, Team Member, Green Team.
* Adds captions to the TOCs so that we get headings in the left menu
* Adds an explicit section on moving between teams and joining the green team.
* Renames a couple things to make them easier to find
closes #192

updating team governance pages

---

docs/team/contributors-binder.yaml
docs/team/contributors-jupyterhub.yaml
docs/team/member-guide.md

This is a first attempt at codifying a team check-in process for team members, following a conversation in #186.
I am hoping that this is perceived as a positive thing by folks - an opportunity for them to decide if they wish to continue in their current roles or move to something else. If folks think that it comes across as pushy or unreasonable, please do not hesitate to give that feedback.
Am happy to iterate on language, specific processes, etc. I imagine there is still a bit of discussion to have around this.

[WIP] adding team check-in process

---

.gitignore
docs/building-blocks/readme-badges.md
docs/index-building_blocks.rst
docs/index.rst

This is a PR to implement the idea of documenting standardized building blocks, allowing us to copy-paste from a central location and document the details regarding typical recurring implementations across our git repositories.
This is the first among many that I think we should centralize a building block for. I considered referring to them instead as "patterns", "practices", "standards" and more, I'm very open to other suggestions but in this WIP I referred to them as standard building blocks.
It would be nice to track the adoption of building blocks, but I wouldn't want to do that from the built documentation as that is too rigid to quickly checkbox something. I suggest we create a more flexible document where we track that, for example HackMD. And in this document, we could list our …

The first standard building block: Readme badges

---

docs/team/contributors-binder.yaml

This PR makes a start with moving some people who have not been active and don't expect to become active again in the near future to the green team. As soon as they do become active again they can of course move back to the blue or red team.
The reason for keeping our team assignments somewhat up to date is (like the Python core team says [towards the bottom of this section](https://www.python.org/dev/peps/pep-0013/#membership)) to provide a reasonable estimate of how many people are actively working on the project.
This moves @yuvipanda and @lheagy because I've managed to get hold of them to discuss this before opening the PR. Thanks for being reachable and taking the time to think about this you two :)
There are two more people in the Binder team who I will try and contact privately …

Move people to the green team

---

docs/team/contributors-binder.yaml
docs/team/contributors-jupyterhub.yaml

Moving myself to the green team (following #262).
It doesn't look like we have the same red-blue-green team structure under JupyterHub, so I just went ahead and removed myself completely from the JupyterHub section. Let me know if I missed anything.
Thanks, y'all!

Move myself (Zsailer) to the Green Team

---

docs/team/member-guide.md

Documents the process of moving the support questions on Discourse and the addition of  the `support bot`.
What do people think about this? :sunny:  Is the *members guide* section the right place to add this info?
Relevant refs:
* https://github.com/jupyterhub/jupyterhub/issues/2996
* https://github.com/jupyterhub/team-compass/issues/271
* [April team meeting agenda](https://hackmd.io/u2ghJJUCRWK-zRidCFid_Q?view)

Document the support bot

---

docs/team/skills.md

This PR adds a "resources for learning" section to the very bottom of the skills page and includes a link to the Learning-k8s repo.

Add learning-k8s link to skills page

---

README.md
docs/monthly-meeting/2020-07-16.md
docs/monthly-meeting/monthly_report_index.rst
docs/weekly-reports/weekly_report_index.rst

This PR adds the minutes from the July team meeting and also addresses some points raised by @choldgraf in https://github.com/jupyterhub/team-compass/issues/308#issuecomment-659074261
fixes #308

Add July team meeting minutes

---

README.md
docs/monthly-meeting/2020-11-19.md
docs/monthly-meeting/monthly_report_index.rst

this PR adds the minutes from the November 2020 team meeting to the repo. It also edits the README to note that weekly team reports have been deprecated.
fixes #346

Add November 2020 Team Meeting minutes

---

docs/meetings.rst
docs/monthly-meeting-hpc/2020-11-04.md
docs/monthly-meeting-hpc/2020-12-02.md
docs/monthly-meeting-hpc/monthly_report_index.rst

Adds a directory called `docs/monthly-meeting-hpc`, adds the November HPC meeting to that directory.  No index is added here yet and no attempt is yet made to integrate the docs with the rest of the site.  As mentioned in #352 the initial goal is to formalize the agenda and surface the notes in a central place.  If there are suggestions about how to integrate the notes in the generated site I could work on that.

Add HPC minutes

---

README.md
docs/monthly-meeting/monthly-meeting-template.md

This PR adds links to the Jupyter Code of Conduct in the repo's readme and the template for the monthly meeting.
related #361

Add Code of Conduct to repo and monthly meeting template

---

docs/monthly-meeting-hpc/2021-04-07.md
docs/monthly-meeting-hpc/monthly_report_index.rst

Notes from the April 2021 HPC interest group meeting.  Highlights:
* BatchSpawner release 1.1 🎉 
* Wrapspawner release 1.0.0 was planned and since happened! 🎉 
* @rkdarst asked for help with https://github.com/jupyterhub/jupyterhub/pull/2726 🚧 
* Discussion on start-up times for JupyterLab, anyone have tips to make that faster, and how fast should it be...? 🐎

Add April 2021 notes

---

docs/team/contributors-jupyterhub.yaml

Just keeping my info on the team page up-to-date :) I suspect I will start to get more involved with JupyterHub things as work at 2i2c ramps up

Update Sarah's affiliation on team page

---

docs/index-team_governance.rst
docs/index-team_guides.rst
docs/team/adding-members.rst
docs/team/member-guide.md
docs/team/shared-infrastructure.md

This is a couple of small additions to the Team Compass after recent conversations in the team meeting. It does the following main things:
1. Adds mention of `quay.io` to our onboarding instructions
2. Adds a "shared infrastructure" page and lists a few major pieces of shared infrastructure I could think of (including quay.io)
3. Adds a paragraph to the Team Guide about fostering open communication (and I think this closes https://github.com/jupyterhub/binderhub/issues/178)
4. Also moves the "adding members" (onboarding guide) to our "team guides" rather than "governance"

Add shared infrastructure and add communications to team guide

---

docs/index-team_guides.rst
docs/team/repository-code-standards.md

Closes https://github.com/jupyterhub/team-compass/issues/454
This is the text suggested in https://github.com/jupyterhub/team-compass/issues/454#issuecomment-939319272 with some minor tweaks.

Add initial repo and code standards

---

docs/team/shared-infrastructure.md

This adds some information about the `mybinder.org` domain to our shared infrastructure page, to make it clearer who owns / controls what. It also notes that I am the current owner of `mybinder.org` and makes it clear that this is not what we want for a long-term solution!
I am still trying to switch the contact email for `mybinder.org`'s registration from my personal email to `binder-team@googlegroups.com`. But the confirmation doesn't seem to be coming through. Will follow up on that.
Long-term, we also discussed that we should probably use an email for mybinder.org that has fewer people on it than the entire Binder team, so that we can minimize potential security risks there (since that email can be used to confirm potentially damaging actions like changing that URL's DNS provider). …

Update information about mybinder.org ownership

---

README.md

This PR moves the monthly team meetings to Tuesdays as agreed upon in the last team meeting. The calendar has also been updated.

Move monthly team meetings to Tuesdays

---

docs/index.rst
docs/team/index.rst

At the moment there's no obvious link to the meetings

Add meetings index to main page

---

docs/index-team_guides.rst
docs/team/community-strategy.md

Adds a sub-page to our docs to gather information on the CSL role. Provides a brief update on thinkings/activities so far.
This is super bare bones to begin with. Happy to tweak format as needed.

Add a community strategy sub-page and provide a brief update on works so far

---

docs/conf.py
docs/practices/communication.md
docs/team/structure.md

This documents our preferred practices for communicating with the JupyterHub Team Council.
- closes #598

Document how to get in touch with the JupyterHub Team Council

---

docs/resources/shared-infrastructure.md

Now that we know that we control the `@jupyterhub` npm organization, this is a PR to document it.
- closes https://github.com/jupyterhub/team-compass/issues/562

Document shared NPM organization

---

docs/conf.py
docs/meetings/community/2018-07-19.md
docs/requirements.txt

A lot of the meeting notes use unformatted URLs e.g. 
`This HackMD: https://hackmd.io/@sgibson91/hubs-team-meeting`
These URLs currently aren't hyperlinked. The linkify extension will convert `scheme://urls` text to hyperlinks.
Alternatively we could go through all our notes and convert `https://url` to [`<https://url>`](https://myst-parser.readthedocs.io/en/latest/syntax/syntax.html#commonmark) and remember to convert them when writing future notes but this is easier.

Auto-linkify full URLs

---

docs/index-team_policies.md
docs/practices/releases.md
docs/resources/shared-infrastructure.md

In #524 I noticed that @consideRatio added a `jupyterhub-bot` as an owner on our PyPI package. This isn't documented anywhere in our team compass but seems pretty important. So this PR adds lightweight documentation about it and a new (and mostly empty) releases section.

Document the jupyterhub bot

---

docs/meetings/hpc/2023-04-05.md
docs/meetings/hpc/index.md

This month:
- [jupyter-lmod](https://github.com/cmd-ntrf/jupyter-lmod) news: Contributions are being made to make it work with tcl too
- Encourage to test jupyterhub-traefik-proxy 1.0 beta
- HPC tag on Discourse?
- Batchspawner test matrix work (sqlalchemy vs python versions)
- Wrapspawner PR merged realtime
- Workshop/conference roundup

HPC notes for 2023 04 05

---

docs/index-team_policies.md
docs/practices/funding.md
docs/practices/pull_requests.md

This documents how we can file reimbursements with NumFocus, and also adds a page documenting the funding currently available to the project.
- closes: https://github.com/jupyterhub/team-compass/issues/646

Document funding sources and how to file a reimbursement

---

docs/meetings/collab-cafe/2023.md
docs/meetings/collab-cafe/index.md
docs/meetings/index.md

Adds some documentation to the team compass on the collaboration cafe, particularly around hosting so that I am not on the critical path
I think with this merge, we can close #617

Add docs on the collaboration cafe meeting

---

.readthedocs.yaml
docs/practices/releases.md
docs/resources/shared-infrastructure.md
docs/team/structure.md

These are updates to offload individual RELEASE.md files have this kind of info (which then would get outdated over time across many separate projects), and to make it more official than to link to a github issue as done before.
I bundled another semi-related commit in this PR because I didn't think it was important enough to create a dedicated one. That was to make updates to describe that the PyPI jupyterhub-bot account, which has lost a lot of its purpose now that PyPI supports giving temporary credentials to a github workflow.
Preview of PRs changes:
- https://jupyterhub-team-compass--679.org.readthedocs.build/en/679/practices/releases.html
- https://jupyterhub-team-compass--679.org.readthedocs.build/en/679/resources/shared-infrastructure.html
- …

Update release practices with info about use of github-activity etc

---

.github/ISSUE_TEMPLATE/collab_cafe.md

I think this is why the template in this repo isn't overriding the defaults from the .github repo

Fix duplicated key in issue template

---

docs/_data/contributors/contributors-jupyterhub.yaml
docs/_data/contributors/gen_contributors.py
docs/team/structure.md

implementation of #752 which has more details on the proposal. Feel free to ask questions here or there if there are any questions or concerns with (or especially objections to!) the proposal.
If this is merged, I'll go ahead and add jupyterhealth to the Jupyter GitHub Enterprise and consider the process complete
Any more tasks to take?

create JupyterHealth team

---

docs/index.md
noxfile.py

I had a conversation with @mfisher87 where he noted that it wasn't clear whether our team compass was just for current team members, or was also for those who wanted to contribute. So this adds a big button to the landing page that is meant to point new contributors in the right direction

Add a link for new contributors

---

docs/_data/contributors/contributors-jupyterhub.yaml

Hi everyone,
I wanted to let you know that I’ve decided to step away from my role as a maintainer for the time being. This hasn’t been an easy decision, but personal stress has been building for a while, and I need to focus on getting things in my life back into balance.
This isn’t necessarily a permanent departure. I’m giving myself the space to take a proper break, sort things out, and then reassess. Once I’m in a better place, I’ll make a clearer decision about whether or not I return in a full capacity.
Being part of this project and community has meant a lot to me. I’m proud of what we’ve built together, and I’m deeply grateful to everyone who’s supported me along the way.
Thanks so much for your understanding and support.
Take care,
Sarah ❤️

Sarah stepping back

---

.readthedocs.yaml

This should have been part of https://github.com/jupyterhub/team-compass/pull/782 but I forgot it.

Configure RTD to use dirhtml builder

---

docs/resources/shared-infrastructure.md

I need to create a new token for https://github.com/jupyterhub/mybinder.org-deploy/blob/bab0a754590ee1aa9fdd5de023411be4edd57d28/.github/workflows/update-grafana-data.yaml
but I don't have access to the bot account, and I realised it's not documented.

Document GitHub @jupyterhub-bot

---

docs/meetings/collab-cafe/index.md

We must have done a re-structure in The Turing Way and not caught this change!

Fix broken link to Turing Way collaboration cafe
