jupyterhub/team-compass

README.md

I didn't add my "roles" in the teams because...I'm not really sure how to define my role in the teams :-P
that's an interesting question, thoughts?

Add myself to the readme

---

README.md

I also reordered people by surname as the text suggests.

Add Tim's name

---

README.md

Adding myself to the readme

---

docs/weekly-reports/team-meeting.md

Follow up to issue re: monthly agenda items #14 cc/ @choldgraf

Reorder team meeting agenda template

---

docs/weekly-reports/2018-01-26_weekly_report.md
docs/weekly-reports/weekly_report_index.rst

We missed a couple of weeks, so I just increased the "start" and "end" times for the report :-)

adding january 26 weekly report

---

README.md

adds a cauldron badge and a link just before the "pr / issues stats" section

Adding cauldron links

---

docs/index.rst

adds an iframe to show cauldron statistics (the overview dashboard anyway) on our team compass page

adding cauldron iframe

---

README.md

Link to a blank agenda for the monthly meeting.

Add link to monthly meeting agenda

---

docs/monthly-meeting/2018-11-15.md
docs/monthly-meeting/monthly_report_index.rst

adding nov meeting

---

readthedocs.yml

Add a readthedocs config file

---

docs/monthly-meeting/2019-02-21.md
docs/monthly-meeting/monthly-meeting-template.md
docs/monthly-meeting/monthly_report_index.rst

Added today's meeting notes to the docs. 
I also updated meeting template (it was out-of-date from our current format).

add february meeting notes

---

docs/monthly-meeting/2019-04-11.md
docs/monthly-meeting/monthly_report_index.rst

Sorry for the delay here. Here are the meeting notes from last week!

Add April 2019 meeting notes

---

docs/monthly-meeting/2019-05-16.md
docs/monthly-meeting/2019-06-19.md
docs/monthly-meeting/monthly_report_index.rst

Added June's meeting notes and fixed a minor styling issue with May's notes.

Add June's meeting notes

---

docs/scripts/gen_contributors.py

Fix red/blue team links on contributors page.

Update link to governance page.

---

README.md

with alternating time slots at 07:00 and 17:00 UTC.

update meeting interval in README

---

docs/team/contributors-jupyterhub.yaml

add georgiana to jupyterhub team

---

docs/team/contributors-jupyterhub.yaml

This adds @manics to the YAML for our team compass "team" page. I wasn't sure what to put for affiliation, or for "areas of work". Simon, if you like could you suggest values for this?

adding simon to team

---

docs/team/contributors-binder.yaml
docs/team/contributors-jupyterhub.yaml

I've updated (read: finally filled in) the tasks for my membership as well as added myself to the JupyterHub team.
I am not super happy with the list of tasks I added to myself. It would be great if there was a "a little bit of everything and what ever it takes to keep this show on the road' ;)

Update the tasks Tim does

---

docs/monthly-meeting/2019-11-21.md
docs/monthly-meeting/monthly_report_index.rst

closes https://github.com/jupyterhub/team-compass/issues/219

adding new meeting

---

docs/monthly-meeting/2020-02-20.md
docs/monthly-meeting/monthly_report_index.rst

Add feb 2020 meeting

---

docs/monthly-meeting/2020-03-19.md
docs/monthly-meeting/monthly_report_index.rst

Add March meeting minutes

---

docs/monthly-meeting/2020-04-16.md

Add meeting notes from April 2020

---

docs/monthly-meeting/2020-05-21.md
docs/monthly-meeting/monthly-meeting-template.md
docs/monthly-meeting/monthly_report_index.rst

fix #285 
As well as adding the meeting notes, I've updated the meeting template to reflect the one we're actually using :)

Add may meeting notes

---

docs/monthly-meeting/2020-06-18.md
docs/monthly-meeting/monthly_report_index.rst

Hubs Team Meeting: June 2020
Fixes #297

Add monthly meeting notes

---

docs/monthly-meeting/monthly-meeting-template.md

Small update to our meeting template to provide more info/links at the top

Update meeting template

---

docs/monthly-meeting/2020-08-20.md
docs/monthly-meeting/monthly_report_index.rst

Add August teem meeting minutes

---

docs/monthly-meeting/2020-09-17.md
docs/monthly-meeting/monthly_report_index.rst

Add September meeting record

---

docs/monthly-meeting/2020-10-22.md
docs/monthly-meeting/monthly_report_index.rst

Add October 2020 meeting minutes

---

docs/monthly-meeting/2020-12-17.md
docs/monthly-meeting/monthly_report_index.rst

Add December meeting minutes

---

docs/monthly-meeting/2021-01-21.md
docs/monthly-meeting/monthly_report_index.rst

Apologies again that this one ran over!
closes #364

Add Jan 2021 meeting mins to repo

---

docs/monthly-meeting-hpc/2021-02-03.md
docs/monthly-meeting-hpc/monthly_report_index.rst

Also adds the link to the December and February notes.  No quorum January (New Years!)

Add February HPC meeting notes

---

docs/monthly-meeting/2021-02-18.md
docs/monthly-meeting/monthly_report_index.rst

Add February meeting notes to repo

---

docs/conf.py
docs/monthly-meeting/2018-11-15.md
docs/monthly-meeting/monthly-meeting-template.md
docs/requirements.txt
requirements.txt

This switches to using the myst parser, let's see if this fixes #387

myst markdown

---

docs/monthly-meeting-hpc/2021-05-04.md
docs/monthly-meeting-hpc/monthly_report_index.rst

HPC interest group notes for May.  Special presentation on the SDSC reverse proxy service took most of the time.

May 2021 HPC notes

---

docs/monthly-meeting/2021-05-20.md
docs/monthly-meeting/monthly_report_index.rst

Add May's meeting minutes

---

docs/monthly-meeting-hpc/2021-06-02.md
docs/monthly-meeting-hpc/monthly_report_index.rst

I'm only 1 week slow this month!

Notes for June from HPC town

---

docs/monthly-meeting/2021-06-17.md
docs/monthly-meeting/monthly_report_index.rst

Add June 2021's meeting mins

---

docs/monthly-meeting-hpc/2021-07-07.md
docs/monthly-meeting-hpc/monthly_report_index.rst

We had a brief meeting were we looked into a wrapspawner issue and discussed UI customizations.  Rollin will make some kind of blog post or write up on NERSC's setup soon...

Notes for July 2021 (short meeting)

---

docs/monthly-meeting/2021-07-15.md
docs/monthly-meeting/monthly_report_index.rst

Add July's meeting minutes

---

docs/monthly-meeting-hpc/2021-08-04.md
docs/monthly-meeting-hpc/monthly_report_index.rst

HPC notes for August.  Topics included a demo of a prototype service for managing a user's favorite way of launching Jupyter from the hub, NBViewer/notebook cloning deployment, security activities, and batchspawner, wrapspawner maintenance.

August 2021 HPC notes

---

docs/monthly-meeting/2021-08-19.md
docs/monthly-meeting/monthly_report_index.rst

Add meeting minutes from Aug 2021 team meeting

---

docs/monthly-meeting/2021-09-16.md
docs/monthly-meeting/monthly_report_index.rst

Add meeting mins from Sept 2021

---

docs/monthly-meeting-hpc/2021-11-03.md
docs/monthly-meeting-hpc/monthly_report_index.rst

Great meeting with 
- Nice JSC home page show-and-tell, thanks Jens!
- BinderHub in a Box demo, thanks @manics 
- JupyterHub 2.0 discussion and **call for testing**, thanks @minrk

Notes from November 2021

---

docs/monthly-meeting/2021-11-18.md
docs/monthly-meeting/monthly_report_index.rst

Add the November 2021 notes

---

2021-12-01.md
docs/monthly-meeting-hpc/monthly_report_index.rst

Notes from the December HPC meeting

---

docs/team/shared-infrastructure.md

This is a short mention of ReadTheDocs for our infrastructure, as a sort-of close to #306

DOCS: Add note about ReadTheDocs infra

---

docs/monthly-meeting-hpc/2022-01-05.md
docs/monthly-meeting-hpc/monthly_report_index.rst

Highlights: Hub 2.0 testing, next actions on wrapspawner release, workshop/conference discussions.  Short meeting.  Happy New Year!

Notes from HPC meeting, 2022-01-05

---

docs/monthly-meeting/2022-01-20.md
docs/monthly-meeting/monthly_report_index.rst

Add January meeting minutes

---

docs/monthly-meeting-hpc/2022-02-02.md
docs/monthly-meeting-hpc/monthly_report_index.rst

HPC meeting minutes for 2022-02-02

---

docs/monthly-meeting/2022-02-17.md
docs/monthly-meeting/monthly_report_index.rst

Add february meeting minutes

---

docs/monthly-meeting-hpc/2022-04-06.md
docs/monthly-meeting-hpc/monthly_report_index.rst

Fun meeting with a discussion of some upcoming contributions to `wrapspawner`, the regular check in on projects, conference/workshop news, and a discussion about Dask-Gateway in HPC.  Great meeting!

Notes from 2022-04-06 HPC meeting

---

docs/monthly-meeting/2022-04-21.md
docs/monthly-meeting/monthly_report_index.rst

Closes https://github.com/jupyterhub/team-compass/issues/500

April 2022 JupyterHub Team Meeting notes

---

docs/monthly-meeting-hpc/2022-05-04.md
docs/monthly-meeting-hpc/monthly_report_index.rst

Notes from the May 5 2022 meeting on HPC + JupyterHub.

Hpc 2022 05

---

docs/meetings/hpc/2022-06-01.md
docs/meetings/hpc/2022-07-06.md
docs/meetings/hpc/index.rst

Late posting of notes from June, but more timely July ones.  The July notes include a show+tell from @rpwagner about his experiences deploying a hub for instructors that involved using Globus that was quite interesting.

HPC notes for June, July 2022

---

docs/meetings/community/2022-07-19.md
docs/meetings/community/index.rst

Closes https://github.com/jupyterhub/team-compass/issues/535

July 2022 meeting notes

---

docs/meetings/hpc/2022-08-03.md
docs/meetings/hpc/index.rst

News on namespacing + jupyter-server-proxy, discussions about open issues and PRs on batchspawner/wrapspawner, workshops planning and planning future discussions

August 2022 HPC notes

---

docs/meetings/community/2022-08-16.md
docs/meetings/community/index.rst

Add August meeting notes

---

docs/meetings/hpc/2022-09-07.md
docs/meetings/hpc/index.rst

Mostly discussion centered around batchspawner release and maintenance this time.

Notes from HPC meeting September 2022

---

docs/meetings/community/2022-09-20.md
docs/meetings/community/index.rst

Add September meeting notes

---

docs/team/community-strategy.md

Small updates to links and pulling in the new project board

DOC: Update Community Strategy page links

---

docs/meetings/hpc/2022-10-05.md
docs/meetings/hpc/index.rst

Summary: portwrap, batchspawner/wrapspawner check-in, community organization

HPC Notes for Oct 2022

---

docs/meetings/community/2022-11-15.md
docs/meetings/community/index.rst

Closes https://github.com/jupyterhub/team-compass/issues/576

Notes for November 2022 JupyterHub team meeting

---

docs/meetings/hpc/2022-11-02.md
docs/meetings/hpc/index.md

A bit behind on posting these 😬

HPC notes 2022-11-02

---

docs/meetings/hpc/2023-01-04.md
docs/meetings/hpc/index.md

Progress on portwrap + singleuser integration, and discussion of stopping spawning servers.

HPC notes 2023 01 04

---

docs/meetings/community/2023-01-17.md
docs/meetings/community/index.md

Add meeting notes for Jan 2023 community meeting

---

docs/meetings/hpc/2023-02-01.md
docs/meetings/hpc/index.md

Highlights: Portwrap progress, plans for Batchspawner this month, discussion on logging and activity monitoring

HPC notes 2023 02 01

---

docs/meetings/community/2023-02-21.md
docs/meetings/community/index.md

Add February 2023 meeting notes

---

docs/meetings/hpc/2023-03-01.md
docs/meetings/hpc/index.md

Some portwrap news, progress on batchspawner and wrapspawner, demo of a Jupyter Slurm provisioner.

HPC meeting notes from 2023-03-01

---

docs/_data/contributors/contributors-jupyterhub.yaml

Move betatim to inactive section

---

docs/meetings/hpc/2023-05-03.md
docs/meetings/hpc/index.md

Notes from our meeting a couple weeks ago

2023-05-03 HPC notes

---

docs/meetings/hpc/2023-06-07.md
docs/meetings/hpc/index.md

JupyterCon recap, HPC tag on Discourse plans, KubeSpawner discussion, other conference/workshop plans

2023-06-07 HPC JupyterHub meeting notes

---

docs/meetings/hpc/2023-07-05.md
docs/meetings/hpc/index.md

Short meeting.  Thanks @consideRatio for the maintenance work on Batchspawner!

HPC notes from 2023-07-05

---

.readthedocs.yaml

Update RTD config to new v2 schema

---

docs/meetings/collab-cafe/2023.md

Archive July 2023 Collab Cafe notes

---

docs/meetings/hpc/2023-08-02.md
docs/meetings/hpc/index.md

HPC notes from August 2023 meeting

---

docs/meetings/hpc/2023-09-06.md
docs/meetings/hpc/index.md

Includes an interesting discussion of issues encountered running Jupyter on Lustre-based home directories, a more detailed report may be coming in a future Discourse post.

HPC notes from 2023-09-06

---

docs/meetings/collab-cafe/2023.md

Add notes from September's Collab Cafe

---

docs/meetings/hpc/2023-11-01.md
docs/meetings/hpc/index.md

BatchSpawner release imminent, report-out on TrustedCI NSF Cybersecurity summit including work on Jupyter + Zeek

HPC meeting notes from 2023-11-01

---

docs/meetings/collab-cafe/2023.md

Add October Collab Cafe notes

---

docs/meetings/community/2023-09-29-maintenance-planning.md
docs/meetings/community/index.md

related https://github.com/jupyterhub/team-compass/issues/680

Add maintenance meeting notes

---

docs/meetings/collab-cafe/2023.md

Add November Collab Cafe notes

---

docs/meetings/collab-cafe/2024.md
docs/meetings/collab-cafe/index.md

Start new file for collab cafe 2024 archive and add January notes

---

docs/meetings/collab-cafe/2024.md

Add February Collab Cafe notes

---

docs/meetings/collab-cafe/2024.md

Add March Collab Cafe notes

---

docs/meetings/collab-cafe/2024.md

Add May Copllab Cafe notes

---

.github/ISSUE_TEMPLATE/collab_cafe.md

This saves me some copy-pasting as I go through this task

Add an issue template for setting up a Collab Cafe event

---

docs/meetings/collab-cafe/2024.md

Add July 2024 Collab Cafe notes

---

docs/meetings/collab-cafe/2024.md

Add collab cafe notes for Aug 2024 meeting

---

docs/meetings/collab-cafe/2024.md

Add notes from Sept 2024 collab cafe

---

docs/meetings/hpc/2023-12-06.md
docs/meetings/hpc/index.md

BatchSpawner release discussions, catch up on recent conference news, demo of a hard-to-ignore notification for use when hardware is about to be shutdown (or possibly when a job is about to end), and JupyterHub/HPC Q+A

Notes from HPC 2023-12-06 meeting

---

docs/meetings/collab-cafe/2024.md

Add collab cafe oct 2024 entry

---

docs/meetings/collab-cafe/2024.md

Add Nov 2024 collab cafe notes to archive

---

docs/meetings/collab-cafe/2024.md
docs/meetings/collab-cafe/2025.md

Closes #754 
Let me know if I've not captured these correctly! First timer here 😅 
Thanks again to everyone for covering me when I had terrible internet!

Add notes from January collaboration cafe

---

docs/meetings/collab-cafe/2025.md

small meeting, mostly spent discussing security-related work

add meeting notes 2025-02-18

---

docs/_data/contributors/contributors-jupyterhub.yaml

Hello JupyterHub Hive Mind!
I have not ever participated meaningfully in JupyterHub development, and one of the reasons I joined this council was to ensure that we get a chance to exercise all of the "paths" (particularly for removing inactive members, like me). Though that hasn't happened, it's probably overdue to have a check in with everyone else, but I thought I'd just remove myself in the meantime.
Wishing you all the very best,
pi

@ivanov stepping down

---

docs/index.md

both needed an update
closes #778

update badge links in docs

---

docs/meetings/collab-cafe/2025.md

Add may notes

---

docs/meetings/collab-cafe/2025.md

Add June collaboration cafe notes 

---

docs/_data/contributors/contributors-jupyterhub.yaml

as co-PI of the overarching project
cc @maryamv

add Ida to Health team

---

docs/meetings/collab-cafe/2025.md

July notes to add to the compass.

Update with notes from July ColabCafe

---

docs/meetings/collab-cafe/2025.md

Notes added to the 2025 running doc.
Closes #806

Add collab cafe notes for 16 and 17 Sept 2025

---

docs/meetings/collab-cafe/2025.md

Add notes for aux collab cafe 24 Sept 2025

---

.github/ISSUE_TEMPLATE/collab_cafe.md
docs/index.md
docs/meetings/collab-cafe/facilitator-checklist.md
docs/meetings/collab-cafe/index.md
docs/meetings/index.md

I've tried to do a pass through the team compass docs to bring the Collaboration Cafe information up to date.
There are a few questions in there that I'm not sure about - I can remove those comments once I have a review 🙏 
I haven't tried to build the docs website locally so I've probably missed some formatting requirements.... so maybe if folks can review separately for content and for rendering that would be super helpful.
(And maybe please just fix the rendering problems 😅 🙏 )
There's quite substantial changes to the content so I'm really keen to get some eyes on those - in particular making clear what the _purpose_ of the meetings are.....

Update documentation for new Collaboration Cafe times and norms
